{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "weave-flux.serviceAccountName" . }}
  labels:
    app: {{ template "weave-flux.name" . }}
    chart: {{ template "weave-flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
