sudo: required

# We need systemd for kubeadm
dist: xenial

language: go

env:
  - DEP_VERSION="0.5.0"
  - MINIKUBE_WANTUPDATENOTIFICATION=false
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - CHANGE_MINIKUBE_NONE_USER=true

go:
  - 1.10.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - mkdir -p $HOME/.kube
  - touch $HOME/.kube/config
  - ./download-prereqs.sh

install:
  - dep ensure
  - sudo -E ./bin/minikube start --kubernetes-version v1.10.6
  - for i in {1..150}; do ./kubectl get po &> /dev/null; if [ $? -ne 1 ]; then break fi; sleep 2; done

script:
  - go test -tags integration_test 
