sudo: required

# We need systemd for kubeadm
dist: xenial

language: go

env:
  - DEP_VERSION="0.5.0" MINIKUBE_WANTUPDATENOTIFICATION=false MINIKUBE_WANTREPORTERRORPROMPT=false CHANGE_MINIKUBE_NONE_USER=true

go:
  - 1.10.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - mkdir -p $HOME/.kube
  - touch $HOME/.kube/config
  - ./download-prereqs.sh

install:
  - dep ensure
  - ./bin/minikube config set WantKubectlDownloadMsg false
  - sudo -E ./bin/minikube start --kubernetes-version v1.10.6 --vm-driver=none --bootstrapper=kubeadm
  - for i in {1..150}; do if ./bin/kubectl get po &> /dev/null; then break; fi; sleep 2; done

script:
  - go test -tags integration_test -minikube-driver none