version: 2
jobs:
  build:
    machine: true
    environment:
      DEP_VERSION: "0.5.0"
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      CHANGE_MINIKUBE_NONE_USER: true
      GOPATH: /tmp/go
    steps:
      - checkout:
          path: /tmp/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          command: sudo apt-get -qq update
      - run:
          command: sudo apt-get install -y socat
      - run:
          command: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $HOME/dep
      - run:
          command: chmod +x $HOME/dep
      - run:
          command: cd /tmp/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME && $HOME/dep ensure
      - run:
          command: mkdir -p $HOME/.kube
      - run:
          command: touch $HOME/.kube/config
      - run:
          command: /tmp/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/download-prereqs.sh
      - run:
          command: echo 'export PATH=/tmp/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/bin:$PATH' >> $BASH_ENV
      - run:
          command: minikube config set WantKubectlDownloadMsg false
      - run:
          command: sudo -E `which minikube` start --kubernetes-version v1.10.6 --vm-driver=none --bootstrapper=kubeadm
      - run:
          command: for i in {1..150}; do if kubectl get pods --all-namespaces; then break; fi; sleep 5; done
      - run:
          command: go test -v -tags integration_test -minikube-driver none $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          command: kubectl logs -n flux -l app=weave-flux-helm-operator