apiVersion: v1
kind: Service
metadata:
  name: {{ template "git-server.fullname" . }}
  labels:
    app: {{ template "git-server.name" . }}
    chart: {{ template "git-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: 2222
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "git-server.name" . }}
    release: {{ .Release.Name }}
